export default [
	"Cambia lingua",
	"Tema chiaro",
	"Tema scuro",
	"Come si gioca?",
	"All'inizio del gioco vengono date 4 carte a ciascun giocatore. Lo scopo del gioco è arrivare a fine partita con il minor punteggio possibile. Le carte hanno il seguente punteggio:",
	"Le 4 carte vengono disposte a rettangolo, come in figura, ma si possono guardare solo quelle più in basso (quelle rosse). Le due carte più in alto rimangono coperte, ossia il giocatore non conosce cosa siano. Inoltre, almeno inizialmente, il giocatore non conosce nessuna delle carte degli avversari.",
	"A questo punto inizia il gioco vero e proprio: a turno i giocatori pescano una carta dal mazzo centrale, e possono scartarla oppure rimpiazzare una di quelle che hanno, anche se è coperta. La carta che è stata rimpiazzata va scartata, rimanendo quindi visibile a tutti i giocatori. La carta appena pescata, invece, rimane visibile solo al giocatore che l’ha pescata.",
	"Nel momento in cui viene scartata una carta, qualsiasi giocatore che abbia una carta con lo stesso numero può buttarla, rimanendo con una carta in meno. Bisogna però fare in fretta, perché il turno passa al giocatore successivo e se questo scarta una nuova carta, diversa dalla precedente, non si può più buttare quella desiderata.",
	'In qualunque momento del suo turno, un giocatore può dire "stop": a quel punto si termina il giro (cioè si continua a giocare fino al giocatore stesso escluso), dopodichè tutte le carte vengono girate, e vince chi ha il punteggio minore, calcolato sommando tutti i punteggi di tutte le carte (visibili e non visibili) del giocatore. Il gioco termina anche quando un giocatore finisce le carte: anche in tal caso si continua il giro finchè non tocca al giocatore senza carte, che non gioca più.',
	"Quando una delle seguenti carte viene pescata dal mazzo e immediatamente scartata, il giocatore può fare l'azione corrispondente (ma può anche decidere di non farla):",
	"guardare una delle sue carte che ancora non conosce (la vedrà solo lui, non gli altri giocatori).",
	"guardare una delle carte degli avversari che lui ancora non conosce (la vedrà solo lui, non gli altri giocatori).",
	"scambiare una delle sue carte con una carta di un avversario.",
	"guardare una carta di un avversario, dopodichè decidere se scambiarla con una delle sue o no.",
	'In ogni caso il giocatore può conoscere solamente il valore delle carte che ha "già visto": per esempio nel caso di uno scambio tramite un J, se il giocatore prende da un avversario una carta che il giocatore stesso non ha ancora visto, non potrà guardarla, se non giocando un 8 dal mazzo (oppure sostituendola e scartandola).',
	"Chiudi",
	"Posizionamento delle carte",
	"Palette cromatica",
	"Scegli un nickname:",
	"Nickname non più disponibili:",
	"Entra",
	"La connessione al server si è interrotta.",
	"Clicca qui",
	"per tornare alla pagina del login.",
	"Se è successo più di una volta di seguito, si prega di contattare l'amministratore del server.",
	"Per favore inserire un nickname.",
	"Il nickname",
	"è già stato utilizzato da un altro giocatore",
	"Tu",
	"giocatore pronto",
	"giocatore non pronto",
	"La partita inizierà quando tutti i giocatori collegati (almeno due) saranno pronti.",
	"Sono pronto",
	"Non sono pronto",
	"Tocca a",
	"Se vuoi puoi selezionare una tua carta coperta per vederla, altrimenti ",
	"Se vuoi puoi selezionare una carta coperta di un avversario per vederla, altrimenti ",
	"Se vuoi puoi selezionare una tua carta e una di un avversario per scambiarle, altrimenti ",
	"Se vuoi puoi vedere una carta di un avversario e decidere se scambiarla con una delle tue, altrimenti ",
	"ha",
	"hai",
	"finito le carte. La partita finirà quando toccherà di nuovo a",
	"te",
	"lui/lei",
	"detto stop. La partita finirà quando toccherà di nuovo a",
	"La partita è finita. Tra poco sarà rivelata la classifica",
	"Classifica",
	"posizione",
	"giocatore",
	"punteggio",
	"Torna alla pagina di login",
	"mostra classifica",
	"nascondi classifica",
	"Quando è il tuo turno, clicca sul mazzo a sinistra per pescare una carta. A questo punto puoi cliccare sul mazzo degli scarti (a destra) per scartarla, oppure cliccare su una tua carta per scambiarla.",
	"Quando scarti un 8, puoi cliccare su una tua carta coperta per vederla, oppure cliccare sul pulsante in alto (che appare automaticamente quando si scarta una carta \"speciale\") per decidere di non farlo.",
	"Quando scarti un 9, puoi cliccare su una carta avversaria coperta per vederla, oppure cliccare sul pulsante in alto per decidere di non farlo.",
	"Quando scarti un J, puoi cliccare su una tua carta e su una carta avversaria per scambiarle, oppure cliccare sul pulsante in alto per decidere di non farlo (anche quando hai già selezionato una delle due carte).",
	"Quando scarti un Q, puoi cliccare su una carta avversaria per vederla, o se è già visibile per scambiarla. Dopodichè puoi cliccare su una tua carta per scambiarle. In qualsiasi momento puoi anche cliccare sul pulsante in alto per decidere di non guardare la carta o non fare lo scambio.",
	"Quando non tocca a te e vuoi buttare una carta, ti basta cliccarla. Se vuoi buttare una carta quando tocca a te è importante che la butti prima di pescare.",
	'Quando vuoi dire STOP e sei all’interno del tuo turno, premi il pulsante in basso a sinistra. Fai attenzione però, perchè il tuo turno finisce quando inizia quello successivo: se è uscito il popup "Tocca a ..." non potrai dire STOP fino al turno successivo.',
	"Come giocare su questo sito",
	"Come funziona il gioco",
	"Se vuoi puoi selezionare una tua carta e scambiarla con quella selezionata, altrimenti ",
	"Se vuoi puoi selezionare una carta avversaria e scambiarla con quella selezionata, altrimenti ",
	"(Il mazzo era finito, sono state rimescolate le carte scartate)",
	"È stato raggiunto il limite massimo di giocatori (6)",
	"Esempio: supponiamo che il giocatore conosca due delle sue carte, rispettivamente un 4 e un 7. Il giocatore pesca dal mazzo una carta con valore molto alto (ad es. Q). A questo punto non conviene rimpiazzare una carta conosciuta (ossia 4 oppure 7) con quella nuova, perché il valore delle sue carte aumenterà (ricorda: scopo del gioco è minimizzare il valore delle carte). D’altro canto, non conviene neanche rimpiazzare una delle due carte di cui non conosce il valore, perché la probabilità che queste due carte abbiano un valore migliore di quella pescata è molto alta. In questo caso, al giocatore conviene scartare la carta pescata.",
	'Esempio. Supponiamo un giocatore rimanga con 2 carte, il cui valore è rispettivamente A e 3. Tutti gli altri giocatori hanno almeno 3 carte. A questo punto è molto probabile che, in quel momento, sia lui ad avere il punteggio migliore di tutti e pertanto è conveniente dire "STOP". Attenzione però: il giro non termina quando si dice "STOP", quindi la situazione può ancora cambiare. Ad esempio, un altro giocatore potrebbe scambiare delle carte (vedi sotto), ribaltando completamente la situazione.',
	"Finito il gioco, quando viene mostrata la classifica, in basso a sinistra trovi un pulsante per nascondere la classifica e vedere scoperte tutte le carte di tutti i giocatori"
];

// Indice della frase è riga-2
